# Generated by Django 5.1.6 on 2025-04-05 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Аэропрт')),
                ('code_name', models.CharField(help_text='FRU', max_length=3, verbose_name='Код аэропорта')),
            ],
            options={
                'verbose_name': 'Аэропорт',
                'verbose_name_plural': 'Аэропорты',
            },
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Город')),
                ('code_name', models.CharField(help_text='FRU', max_length=3, verbose_name='Код города')),
                ('aero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airports', to='avia.airports')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Страна')),
                ('code_name', models.CharField(max_length=3, unique=True, verbose_name='Код страны')),
                ('img', models.ImageField(upload_to='countries', verbose_name='Флаг')),
                ('cities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='avia.cities', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
    ]
