# Generated by Django 5.1.6 on 2025-04-18 10:18

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('kg', 'Кыргызча'), ('ru', 'Русский'), ('en', 'English')], default='ru', max_length=25, verbose_name='Язык')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='СЛАГ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('kg', 'Кыргызча'), ('ru', 'Русский'), ('en', 'English')], default='ru', max_length=255, verbose_name='Язык')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('answer', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Частые вопросы',
                'verbose_name_plural': 'Частые вопросы',
            },
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('kg', 'Кыргызча'), ('ru', 'Русский'), ('en', 'English')], default='ru', max_length=255, verbose_name='Язык')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='СЛАГ')),
                ('img', models.ImageField(upload_to='informations/', verbose_name='Логотип')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Информация')),
            ],
            options={
                'verbose_name': 'Информация',
                'verbose_name_plural': 'Информации',
            },
        ),
        migrations.CreateModel(
            name='PopularDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('kg', 'Кыргызча'), ('ru', 'Русский'), ('en', 'English')], default='ru', max_length=25, verbose_name='Язык')),
                ('name', models.CharField(max_length=255, verbose_name='Город')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='СЛАГ')),
                ('image', models.ImageField(upload_to='directions/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Популярная направления',
                'verbose_name_plural': 'Популярные направлении',
            },
        ),
        migrations.CreateModel(
            name='SubInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='СЛАГ')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Информация')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subinfo', to='home.information', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Подкатегория информация',
                'verbose_name_plural': 'Подкатегория информации',
            },
        ),
    ]
