# Generated by Django 5.1.6 on 2025-04-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True, verbose_name='СЛАГ'),
        ),
    ]
