# Generated by Django 5.1.6 on 2025-04-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='СЛАГ'),
        ),
    ]
