# Generated by Django 5.1.6 on 2025-03-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_subcategory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='slug',
            field=models.SlugField(default=1, editable=False, unique=True, verbose_name=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=1, editable=False, unique=True, verbose_name=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='populardirection',
            name='slug',
            field=models.SlugField(default=1, editable=False, unique=True, verbose_name=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(default=1, editable=False, unique=True, verbose_name=''),
            preserve_default=False,
        ),
    ]
