# Generated by Django 5.1.6 on 2025-04-23 06:24

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_faq_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='information',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Информация'),
        ),
        migrations.AlterField(
            model_name='subinformation',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Информация'),
        ),
    ]
