# Generated by Django 5.1.6 on 2025-03-18 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_banner_slug_category_slug_populardirection_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Информация в главном экране', 'verbose_name_plural': 'Информации в главном экране'},
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='slug',
        ),
        migrations.AlterField(
            model_name='banner',
            name='slug',
            field=models.SlugField(editable=False, unique=True, verbose_name='СЛАГ'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(editable=False, unique=True, verbose_name='СЛАГ'),
        ),
        migrations.AlterField(
            model_name='populardirection',
            name='slug',
            field=models.SlugField(editable=False, unique=True, verbose_name='СЛАГ'),
        ),
    ]
