# Generated by Django 5.1.6 on 2025-04-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_faq_answer_alter_information_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='background_color',
            field=models.CharField(blank=True, default='#ffffff', help_text='Например, #f0f8ff, red, rgb(255,255,255)', max_length=20, null=True, verbose_name='Цвет фона'),
        ),
    ]
