# Generated by Django 5.1.6 on 2025-04-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_information_background_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='subinformation',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cодержимое'),
        ),
    ]
